# Generated by Django 5.1.6 on 2025-02-11 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StreamPlatform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(auto_created=100)),
                ('name', models.CharField(max_length=30)),
                ('about', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='WatchList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=32)),
                ('storyline', models.TextField()),
                ('genre', models.CharField(max_length=32)),
                ('published', models.BooleanField(default=True)),
                ('year', models.IntegerField()),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
