# Generated by Django 5.1.6 on 2025-02-16 15:58

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0004_reviews'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MaxLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
