# Generated by Django 5.1.6 on 2025-02-16 16:04

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('watchlist_app', '0005_alter_reviews_rating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='WatchList',
            new_name='watchlist',
        ),
        migrations.AlterField(
            model_name='reviews',
            name='rating',
            field=models.PositiveIntegerField(validators=[django.core.validators.MinLengthValidator(1), django.core.validators.MaxLengthValidator(5)]),
        ),
    ]
